// flow-typed signature: dde244f8ebc705b247502115f23e82c0
// flow-typed version: <<STUB>>/tar.gz_v^1.0.5/flow_v0.43.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tar.gz'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'tar.gz' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'tar.gz/index' {
  declare module.exports: $Exports<'tar.gz'>;
}
declare module 'tar.gz/index.js' {
  declare module.exports: $Exports<'tar.gz'>;
}
