// flow-typed signature: db2366517a6dab39ef8a21ac8fcd6043
// flow-typed version: <<STUB>>/uglifyjs_v^2.4.10/flow_v0.43.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'uglifyjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'uglifyjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'uglifyjs/lib/ast' {
  declare module.exports: any;
}

declare module 'uglifyjs/lib/compress' {
  declare module.exports: any;
}

declare module 'uglifyjs/lib/mozilla-ast' {
  declare module.exports: any;
}

declare module 'uglifyjs/lib/output' {
  declare module.exports: any;
}

declare module 'uglifyjs/lib/parse' {
  declare module.exports: any;
}

declare module 'uglifyjs/lib/scope' {
  declare module.exports: any;
}

declare module 'uglifyjs/lib/sourcemap' {
  declare module.exports: any;
}

declare module 'uglifyjs/lib/transform' {
  declare module.exports: any;
}

declare module 'uglifyjs/lib/utils' {
  declare module.exports: any;
}

declare module 'uglifyjs/tools/node' {
  declare module.exports: any;
}

// Filename aliases
declare module 'uglifyjs/lib/ast.js' {
  declare module.exports: $Exports<'uglifyjs/lib/ast'>;
}
declare module 'uglifyjs/lib/compress.js' {
  declare module.exports: $Exports<'uglifyjs/lib/compress'>;
}
declare module 'uglifyjs/lib/mozilla-ast.js' {
  declare module.exports: $Exports<'uglifyjs/lib/mozilla-ast'>;
}
declare module 'uglifyjs/lib/output.js' {
  declare module.exports: $Exports<'uglifyjs/lib/output'>;
}
declare module 'uglifyjs/lib/parse.js' {
  declare module.exports: $Exports<'uglifyjs/lib/parse'>;
}
declare module 'uglifyjs/lib/scope.js' {
  declare module.exports: $Exports<'uglifyjs/lib/scope'>;
}
declare module 'uglifyjs/lib/sourcemap.js' {
  declare module.exports: $Exports<'uglifyjs/lib/sourcemap'>;
}
declare module 'uglifyjs/lib/transform.js' {
  declare module.exports: $Exports<'uglifyjs/lib/transform'>;
}
declare module 'uglifyjs/lib/utils.js' {
  declare module.exports: $Exports<'uglifyjs/lib/utils'>;
}
declare module 'uglifyjs/tools/node.js' {
  declare module.exports: $Exports<'uglifyjs/tools/node'>;
}
