// flow-typed signature: 9857d46c8f901d8f9949e90ae1f4c6c1
// flow-typed version: <<STUB>>/zlib_v^1.0.5/flow_v0.43.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'zlib'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'zlib' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'zlib/lib/zlib' {
  declare module.exports: any;
}

declare module 'zlib/test/deflate.test' {
  declare module.exports: any;
}

declare module 'zlib/test/inflate.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'zlib/index' {
  declare module.exports: $Exports<'zlib'>;
}
declare module 'zlib/index.js' {
  declare module.exports: $Exports<'zlib'>;
}
declare module 'zlib/lib/zlib.js' {
  declare module.exports: $Exports<'zlib/lib/zlib'>;
}
declare module 'zlib/test/deflate.test.js' {
  declare module.exports: $Exports<'zlib/test/deflate.test'>;
}
declare module 'zlib/test/inflate.test.js' {
  declare module.exports: $Exports<'zlib/test/inflate.test'>;
}
